const musicData = [
  {
    backgroundImage: "https://pages.souls-music.com/images/poster-1.jpg",
    posterUrl: "https://pages.souls-music.com/images/poster-1.jpg",
    title: "Happy Moments (Master)",
    album: "No Spirit",
    year: 2022,
    artist: "No Spirit x Tonion",
    musicPath: "https://music.souls-music.com/music/music-1.mp3",
  },
  {
    backgroundImage: "https://pages.souls-music.com/images/poster-2.jpg",
    posterUrl: "https://pages.souls-music.com/images/poster-2.jpg",
    title: "We Are Going To Be Ok (Master)",
    album: "No Spirit",
    year: 2022,
    artist: "No Spirit x Jhove",
    musicPath: "https://music.souls-music.com/music/music-2.mp3",
  },
  {
    backgroundImage: "https://pages.souls-music.com/images/poster-3.jpg",
    posterUrl: "https://pages.souls-music.com/images/poster-3.jpg",
    title: "Winter Meadow",
    album: "No Spirit",
    year: 2022,
    artist: "No Spirit x  juniorodeo",
    musicPath: "https://music.souls-music.com/music/music-3.mp3",
  },
  {
    backgroundImage: "https://pages.souls-music.com/images/poster-4.jpg",
    posterUrl: "https://pages.souls-music.com/images/poster-4.jpg",
    title: "From Where We Started",
    album: "No Spirit",
    year: 2022,
    artist: "No Spirit",
    musicPath: "https://music.souls-music.com/music/music-4.mp3",
  },
  {
    backgroundImage: "https://pages.souls-music.com/images/poster-5.jpg",
    posterUrl: "https://pages.souls-music.com/images/poster-5.jpg",
    title: "Where I Found You",
    album: "No Spirit",
    year: 2022,
    artist: "No Spirit",
    musicPath: "https://music.souls-music.com/music/music-5.mp3",
  },
];
